package com.photoz.authz.policy.admin

import org.keycloak.authz.core.policy.evaluation.Evaluation;

rule "Authorize Resource Owner"
    dialect "mvel"
    when
       $evaluation : Evaluation(
           $identity: context.identity,
           $permission: permission,
           $permission.resource != null && $permission.resource.owner.equals("2")
       )
    then
        $evaluation.grant();
end