package com.photoz.authz.policy.admin

import org.keycloak.authz.core.policy.evaluation.Evaluation;

rule "Authorize Resource Owner"
    dialect "mvel"
    when
       $evaluation : Evaluation(
           $permission: permission,
           $context: context,
           $identity: $context.identity,
           $permission.resource != null && $permission.resource.owner.equals($identity.id)
       )
    then
        $evaluation.grant();
end