#!/usr/bin/env bash
cp api/target/keycloak-authz-api-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main/
cp server/services/uma/target/keycloak-authz-server-uma-services-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp server/services/entitlement/target/keycloak-authz-server-entitlement-services-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp server/services/admin/target/keycloak-authz-server-admin-services-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp provider/drools/target/keycloak-authz-drools-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp provider/identity/target/keycloak-authz-identity-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp provider/scope/target/keycloak-authz-scope-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp provider/resource/target/keycloak-authz-resource-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp persistence/api/target/keycloak-authz-persistence-api-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp persistence/jpa/target/keycloak-authz-jpa-provider-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp api/target/keycloak-authz-api-1.0-SNAPSHOT.jar /pedroigor/java/container/jboss/community/keycloak/keycloak-app-server-latest/modules/system/layers/base/org/keycloak/keycloak-authz-uma/main/keycloak-authz-api-1.0-SNAPSHOT.jar
cp server/client/target/keycloak-authz-client-1.0-SNAPSHOT.jar /pedroigor/java/container/jboss/community/keycloak/keycloak-app-server-latest/modules/system/layers/base/org/keycloak/keycloak-authz-client/main/keycloak-authz-client-1.0-SNAPSHOT.jar
cp server/services/uma/target/keycloak-authz-server-uma-services-1.0-SNAPSHOT.jar /pedroigor/java/container/jboss/community/keycloak/keycloak-app-server-latest/modules/system/layers/base/org/keycloak/keycloak-authz-uma/main/keycloak-authz-uma-1.0-SNAPSHOT.jar
cp enforcer/jaxrs/target/keycloak-authz-jaxrs-enforcer-1.0-SNAPSHOT.jar /pedroigor/java/container/jboss/community/keycloak/keycloak-app-server-latest/modules/system/layers/base/org/keycloak/keycloak-authz-uma/main/
cp enforcer/jaxrs/target/keycloak-authz-jaxrs-enforcer-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main
cp enforcer/servlet/target/keycloak-authz-servlet-enforcer-1.0-SNAPSHOT.jar /pedroigor/java/container/jboss/community/keycloak/keycloak-app-server-latest/modules/system/layers/base/org/keycloak/keycloak-authz-uma/main/
cp enforcer/servlet/target/keycloak-authz-servlet-enforcer-1.0-SNAPSHOT.jar /pedroigor/java/workspace/jboss/keycloak/keycloak-authz/distribution/server-dist/target/keycloak-1.0-SNAPSHOT/modules/system/layers/base/org/keycloak/keycloak-authz/main