package com.photoz.authz.policy.admin

import org.keycloak.authz.core.policy.evaluation.Evaluation;
import org.keycloak.authz.policy.provider.drools.api.CallerIdentity;

rule "Authorize Admin Resources"
    dialect "mvel"
        when
           $evaluation : Evaluation(
               $identity : context.identity,
               ((CallerIdentity) $identity).hasRole("user")
           )
        then
           $evaluation.grant();
end