package com.photoz.authz.policy.admin

import org.keycloak.authz.core.policy.Evaluation;

rule "Authorize Resource Owner"
    dialect "mvel"
    when
       $evaluation : Evaluation(
           $executionContext: context.executionContext,
           $executionContext.hasAttribute("kc.authz.context.authc.method", "otp"),
           $executionContext.hasAttribute("someAttribute", "you_can_access")
       )
    then
        $evaluation.grant();
end