package com.photoz.authz.policy.admin

import org.keycloak.authz.core.policy.evaluation.Evaluation;

rule "Authorize Using Context Information"
    dialect "mvel"
    when
       $evaluation : Evaluation(
           $executionContext: context.executionContext,
           $attributes: context.executionContext.attributes,
           $attributes.containsValue("kc.authz.context.authc.method", "otp"),
           $attributes.containsValue("someAttribute", "you_can_access")
       )
    then
        $evaluation.grant();
end